# Use this docker setup in order to get the example database up and running
# setup the .env file for passwords etc.

version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
    - "./db:/docker-entrypoint-initdb.d"